# Starter pipeline
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '2af1a2b43594c073e8854eeef17bb0cb'
    apiKey: '015e5e62e52620215df760ec55b099ab7b855b6dc730a27b3ec7472207a0f53ade187c2a63767c621a3552d10a00b6d10d02ddb8270531624667447bb964ab56'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(build.artifactstagingdirectory)'
    importResults: true
    failBuildOnPolicyFail: true
    maximumWaitTime: '360'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'demo-avalora-veracode'
    replaceExistingArchive: true
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Credentials'
    apiId: '2af1a2b43594c073e8854eeef17bb0cb'
    apiKey: '015e5e62e52620215df760ec55b099ab7b855b6dc730a27b3ec7472207a0f53ade187c2a63767c621a3552d10a00b6d10d02ddb8270531624667447bb964ab56'
    veracodeAppProfile: 'Demo POC veracode'
    version: '$(build.buildNumber)'
    filepath: './demo-avalora-veracode.zip'
    sandboxName: 'Gabriel Acuna'
    importResults: true
    maximumWaitTime: '360'

